### ISSUE TITLE
Deployment is getting failed

### ISSUE THREAD

**Issue by coolpalani** [wako057/openstack-salt#2]
Hello,

When I am trying to execute database state, it's getting failed.
I have pasted logs in below link
https://pastebin.com/mxBpVyKa

Could you lookup and help for fix this issue to move forward.

**Comment by wako057** [comment]
Hello Coolpani

I thinks its more related to minion configuration not the formula itself

Did you configured your minion in order that salt can access the database?

In debian/ubuntu, You have to have to add that line
mysql.default_file: '/etc/mysql/debian.cnf'
In the controller /etc/salt/minion file in order that salt can access mysql

Dont forget to restart the minion

**Comment by wako057** [comment]
Requirement

    A salt Mast
    Minion with salt configured to the master
    The controller minion file should have the following directive in order make the database manipulation possible mysql.default_file: '/etc/mysql/debian.cnf'

**Comment by coolpalani** [comment]
Hello wako057,

Sorry, I have missed that requirement to setup in minion configuration file. my bad.
I have successfully deployed now. This is my deployment through SALTSTACK though used Ansible,RDO packstack

When we use this formula in Virtual based setup, we have to modify this place to create cinder volume in storage node.
https://github.com/wako057/openstack-salt/blob/master/salt/cinder/cinder-storage.sls
https://github.com/wako057/openstack-salt/blob/master/salt/cinder/files/lvm.conf

Thank you very much for your support.

how do we create network through formula. Had you already done or not?

**Comment by wako057** [comment]
indeed, it would be a good idea but no i dont have a formula to create the network
